chmodfacl: Style: Reindent, rename variables, return worst status, complain if args missing

diff --git a/bin/chmodfacl b/bin/chmodfacl
--- a/bin/chmodfacl
+++ b/bin/chmodfacl
@@ -3,33 +3,45 @@
 
 printUsage()
 {
-  cat <<HELPTEXT
+    cat <<HELPTEXT
 Convert chmod octal permission args to equivalent setfacl args.
 HELPTEXT
-  echo
-  printf 'Usage: %q %s\n' "$(basename "$1")" 'OCTAL-MODE [...] [--] FILE [...] [-?|-h|--help]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'OCTAL-MODE [...] [--] FILE [...] [-?|-h|--help]'
 }
 case "$1" in
-  --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
+    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
 esac
 
-
-ARGS=() ; FILES=()
+typeset -a permissionArgs=()
+typeset -a filespecs=()
 while [ $# -gt 0 ]; do
-  A=$1 ; shift
-  case "$A" in
-  600|0600) ARGS+=("u::rw-,g::---,o::---") ;;
-  640|0640) ARGS+=("u::rw-,g::r--,o::---") ;;
-  644|0644) ARGS+=("u::rw-,g::r--,o::r--") ;;
-  700|0700) ARGS+=("u::rwx,g::---,o::---") ;;
-  --) shift; FILES+=("$@"); break;;
-  *) if [ -e "$A" ]; then FILES+=( "$A" ) ; else
-    echo "unrecognized arg [$A]" 1>&2
-    exit 1
-  fi
-  ;;
-  esac
+    case "$1" in
+	600|0600)   shift; permissionArgs+=("u::rw-,g::---,o::---");;
+	640|0640)   shift; permissionArgs+=("u::rw-,g::r--,o::---");;
+	644|0644)   shift; permissionArgs+=("u::rw-,g::r--,o::r--");;
+	700|0700)   shift; permissionArgs+=("u::rwx,g::---,o::---");;
+	--)	    shift; filespecs+=("$@"); break;;
+	*)	    if [ -e "$1" ]; then
+			filespecs+=( "$1" )
+			shift
+		    else
+			echo "ERROR: Unrecognized argument: $1"
+			echo
+			printUsage "$0"
+			exit 1
+		    fi >&2
+		    ;;
+    esac
 done
-for F in "${FILES[@]}" ; do
-  setfacl -s "${ARGS[@]}" "$F"
+if [ ${#permissionArgs[@]} -eq 0 -o ${#filespecs[@]} -eq 0 ]; then
+    printUsage "$0" >&2
+    exit 2
+fi
+
+status=0
+for f in "${filespecs[@]}"
+do
+    setfacl -s "${permissionArgs[@]}" "$f" || status=$?
 done
+exit $status
