Refactoring: Long parsing

diff --git a/bin/expandglob b/bin/expandglob
--- a/bin/expandglob
+++ b/bin/expandglob
@@ -33,10 +33,15 @@ SEE ALSO:
 - hasglobmatch is expandglob without printing the result (and leaving early).
 HELPTEXT
 }
-case "$1" in
-    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-    --)			shift;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
