fileAge: Refactoring: Expand to full command-line argument parsing in order to support passing -- separator

diff --git a/bin/fileAge b/bin/fileAge
--- a/bin/fileAge
+++ b/bin/fileAge
@@ -5,19 +5,27 @@ printUsage()
     cat <<HELPTEXT
 Show the age (in seconds since the Epoch, or seconds with -d|--diff) of all passed FILE(s).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-d|--diff] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-d|--diff] [--] FILE [...] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --diff|-d)
-	shift
-	now="$(date +%s)"
-	while read -r epoch
-	do
-	    printf '%d\n' "$((now - epoch))"
-	done < <(stat -L --format %Y -- "$@")
-	;;
-    *)
-	exec stat -L --format %Y -- "$@"
-	;;
-esac
+
+isDiff=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--diff|-d)	shift; isDiff=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+
+if [ "$isDiff" ]; then
+    now="$(date +%s)"
+    while read -r epoch
+    do
+	printf '%d\n' "$((now - epoch))"
+    done < <(stat -L --format %Y -- "$@")
+else
+    exec stat -L --format %Y -- "$@"
+fi
