fileAge: ENH: Allow --within|--without TIMESLOT
Taken from executionMarker.

diff --git a/bin/fileAge b/bin/fileAge
--- a/bin/fileAge
+++ b/bin/fileAge
@@ -21,6 +21,18 @@ HELPDESCRIPTION
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX] [--] FILE [...]'
     echo
+    cat <<HELPDESCRIPTION
+Test whether the age of [all] FILE[s] falls inside / outside TIMESLOT.
+TIMESLOT can be one of second|minute|hour|day|week|month|year, or
+every N seconds|minutes|hours|days|weeks|months|years|generations, which doesn't
+translate to a fixed age, but instead ensures that this falls into / outside the
+slot.
+For example, 'day' could mean an age difference of only seconds, if the one is
+before midnight and the other shortly after midnight.
+HELPDESCRIPTION
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-w|--within|-W|--without second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks|months|years|generations) [--] FILE [...]'
+    echo
     cat <<HELPTEXT
 EXIT STATUS:
     0	Complete success.
@@ -30,23 +42,45 @@ EXIT STATUS:
 HELPTEXT
 }
 
-timeToSeconds()
+getSpan()
+{
+    local divider="$1"; shift
+    divider="${divider#every }"
+    divider="${divider% +([a-z])}"
+    printf '%d' "$divider"
+}
+parseTime()
 {
     case "$1" in
-	+([0-9])?(s))   age="${1%s}";;
-	+([0-9])m)	age=$((${1%m} * 60));;
-	+([0-9])h)	age=$((${1%h} * 3600));;
-	+([0-9])d)	age=$((${1%d} * 86400));;
-	+([0-9])w)	age=$((${1%w} * 86400 * 7));;
-	+([0-9])mo)	age=$((${1%mo} * 86400 * 30));;
-	+([0-9])y)	age=$((${1%y} * 86400 * 365));;
-	+([0-9])g)	age=$((${1%g} * 86400 * 9131));;
-	*)		printf >&2 'ERROR: Illegal age: %s\n' "$1"; exit 2;;
+	+([0-9])?(s))			age="${1%s}";;
+	+([0-9])m)			age=$((${1%m} * 60));;
+	+([0-9])h)			age=$((${1%h} * 3600));;
+	+([0-9])d)			age=$((${1%d} * 86400));;
+	+([0-9])w)			age=$((${1%w} * 86400 * 7));;
+	+([0-9])mo)			age=$((${1%mo} * 86400 * 30));;
+	+([0-9])y)			age=$((${1%y} * 86400 * 365));;
+	+([0-9])g)			age=$((${1%g} * 86400 * 9131));;
+	second)				timeformat='%s';;
+	minute)				timeformat='%F_%H:%M';;
+	hour)				timeformat='%F_%H';;
+	day)				timeformat='%F';;
+	week)				timeformat='%G_%V';;
+	month)				timeformat='%Y_%m';;
+	year)				timeformat='%Y';;
+	every\ +([0-9])\ seconds)	age="$(getSpan "$1")"; timedivider=1;;
+	every\ +([0-9])\ minutes)	age="$(getSpan "$1")"; timedivider=60;;
+	every\ +([0-9])\ hours)		age="$(getSpan "$1")"; timedivider=3600;;
+	every\ +([0-9])\ days)		age="$(getSpan "$1")"; timedivider=86400;;
+	every\ +([0-9])\ weeks)		age="$(getSpan "$1")"; timedivider=$((86400 * 7));;
+	every\ +([0-9])\ months)	age="$(getSpan "$1")"; timedivider=$((86400 * 30));;
+	every\ +([0-9])\ years)		age="$(getSpan "$1")"; timedivider=$((86400 * 365));;
+	every\ +([0-9])\ generations)	age="$(getSpan "$1")"; timedivider=$((86400 * 9131));;
+	*)				printf >&2 'ERROR: Invalid age/TIMESLOT: "%s".\n' "$1"; printUsage "$0" >&2; exit 2;;
     esac
-    printf %s "$age"
 }
 
-compareOp=
+spanCompareOp=
+formatCompareOp=
 isDiff=
 formatAddendum=
 while [ $# -ne 0 ]
@@ -56,16 +90,18 @@ do
 	--diff|-d)	shift; isDiff=t;;
 	--with-filename|-f)
 			shift; formatAddendum=$'\t%n';;
-	--newer|-n)	shift; age="$(timeToSeconds "$1")" || exit $?; shift; compareOp=-lt;;
-	--older|-o)	shift; age="$(timeToSeconds "$1")" || exit $?; shift; compareOp=-gt;;
+	--newer|-n)	shift; parseTime "$1"; shift; spanCompareOp=-lt;;
+	--older|-o)	shift; parseTime "$1"; shift; spanCompareOp=-gt;;
 	-lt|-le|-eq|-ne|-ge|-gt)
-			compareOp="$1"; shift; age="$(timeToSeconds "$1")" || exit $?; shift;;
+			spanCompareOp="$1"; shift; parseTime "$1"; shift;;
+	--within|-w)	shift; parseTime "$1"; spanCompareOp='-ge'; formatCompareOp='='; shift;;
+	--without|-W)	shift; parseTime "$1"; spanCompareOp='-le'; formatCompareOp='!='; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
-typeset -a requiredArgs=(-ge 1); [ -n "$compareOp" ] && requiredArgs=(-eq 1)
+typeset -a requiredArgs=(-ge 1); [ -n "$spanCompareOp" ] && requiredArgs=(-eq 1)
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
@@ -75,8 +111,27 @@ getEpoch()
 {
     stat --dereference --format "%Y${formatAddendum}" -- "$@" || return 4
 }
+calculateTimeRange()
+{
+    local epoch="${1:?}"; shift
+    local now="$(date +%s)"
 
-if [ -n "$compareOp" ]; then
+    if [ -n "$timeformat" ]; then
+	local nowTime fileTime
+	nowTime="$(date --date "@$now" "+$timeformat")" || exit 3
+	fileTime="$(date --date "@$epoch" "+$timeformat")" || exit 3
+	[ "$fileTime" $formatCompareOp "$nowTime" ]
+    elif [ -n "$timedivider" ]; then
+	local nowDivision fileDivision
+	nowDivision="$((now / timedivider))"
+	fileDivision="$((epoch / timedivider))"
+	[ $age $spanCompareOp $((nowDivision - fileDivision)) ]
+    else
+	[ $((now - epoch)) $spanCompareOp $age ]
+    fi
+}
+
+if [ -n "$spanCompareOp" ]; then
     if [ -n "$formatAddendum" ]; then
 	echo 'ERROR: Cannot combine -f|--with-filename with AGE comparison.'
 	echo
@@ -84,12 +139,11 @@ if [ -n "$compareOp" ]; then
 	exit 2
     fi >&2
 
-    now="$(date +%s)"
     exitStatus=3
     compareStatus=0
     while IFS=$'\n' read -r epoch || { exitStatus="$epoch"; break; }	# Exit status from the process substitution (<(getEpoch)) is lost; return the actual exit status via an incomplete (i.e. missing the newline) last line.
     do
-	[ $((now - epoch)) $compareOp $age ] || compareStatus=1
+	calculateTimeRange "$epoch" || compareStatus=1
     done < <(getEpoch "$@"; printf %d "$?")
     exit $((exitStatus > 0 ? exitStatus : compareStatus))
 elif [ "$isDiff" ]; then
