fileswap: ENH: Add --atomic swapping through SYS_renameat2 syscall
And just-in-time compilation through the Tiny C Compiler (an interesting approach).

diff --git a/bin/fileswap b/bin/fileswap
--- a/bin/fileswap
+++ b/bin/fileswap
@@ -1,5 +1,4 @@
 #!/bin/bash
-# Source: https://unix.stackexchange.com/a/187552/18876
 
 printUsage()
 {
@@ -7,17 +6,71 @@ printUsage()
 Swap FILE1 and FILE2.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'FILE1 FILE2 [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--atomic] [--] FILE1 FILE2 [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-esac
+action=fileswapEmulated
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
+	--atomic)	    shift
+			    if ! exists tcc; then
+				echo >&2 'FATAL: tcc command not available for atomic swap.}'
+				exit 3
+			    fi
+			    action=fileswapAtomic
+			    ;;
+	--)		    shift; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    break;;
+    esac
+done
 if [ $# -ne 2 ]; then
     printUsage "$0" >&2
     exit 2
 fi
 
-TMPFILE="$(TMPDIR="$(dirname -- "$1")" mktemp)" && \
-    mv --force -- "$1" "$TMPFILE" && \
-    mv --force -- "$2" "$1" && \
-    mv --force -- "$TMPFILE" "$2"
+# Source: https://unix.stackexchange.com/a/187552/18876
+fileswapEmulated()
+{
+    TMPFILE="$(TMPDIR="$(dirname -- "$1")" mktemp)" && \
+	mv --force -- "$1" "$TMPFILE" && \
+	mv --force -- "$2" "$1" && \
+	mv --force -- "$TMPFILE" "$2"
+}
+
+# Source: https://unix.stackexchange.com/a/625900/18876
+fileswapAtomic() {
+    exec tcc -run - "$@" <<"CODE"
+    #include <unistd.h>
+    #include <fcntl.h>
+    #include <stdio.h>
+    #include <sys/syscall.h>
+
+    // Ubuntu 18.04 doesn't define this constant
+    // Obtained from '/usr/include/linux/fs.h'
+    // Always test first! Might not always corispond to userland
+    // RENAME_EXCHANGE
+    int local_RENAME_EXCHANGE = (1 << 1);
+
+    int main(int argc, char **argv) {
+        if (argc != 3) {
+            fprintf(stderr, "Error: Could not swap names. Usage: %s PATH1 PATH2\n", argv[0]);
+            return 2;
+	}
+	int r = syscall(
+            SYS_renameat2,
+            AT_FDCWD, argv[1],
+            AT_FDCWD, argv[2],
+            local_RENAME_EXCHANGE
+	);
+	if (r < 0) {
+            perror("Error: Could not swap names");
+            return 1;
+	}
+	else return 0;
+    }
+CODE
+}
+
+$action "$@"
