Minor: Consistently use printUsage(), add newline before bottom hint, do block-wide redirection

diff --git a/bin/findup b/bin/findup
--- a/bin/findup
+++ b/bin/findup
@@ -15,14 +15,14 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-printf 'Usage: %q %s\n' "$(basename "$1")" "[STARTING-POINT [...]] [-1|--stop-at-first] [--stop-at DIR [...]] [--not-above DIR [...]] [--stopdepth LEVELS] [--mindepth LEVELS] [--maxdepth LEVELS] [--print|--exec COMMAND [...] ;|--execdir COMMAND [...] ;] [--] FILE|'GLOB' [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[STARTING-POINT [...]] [-1|--stop-at-first] [--stop-at DIR [...]] [--not-above DIR [...]] [--stopdepth LEVELS] [--mindepth LEVELS] [--maxdepth LEVELS] [--print|--exec COMMAND [...] ;|--execdir COMMAND [...] ;] [--] FILE|'GLOB' [...] [-?|-h|--help]"
 }
 printUsage()
 {
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -100,7 +100,7 @@ do
 	if [ -e "$1" ]; then
 	    printf >&2 'ERROR: STARTING-POINT is not a directory: %s\n' "$1"
 	    echo >&2
-	    printShortUsage "$0" >&2
+	    printUsage "$0" >&2
 	    exit 2
 	elif startingPoint="$(findExistingStartingPointAbove "$(realpath --no-symlinks -- "$1" 2>/dev/null)")"; then
 	    startingPoints+=("$startingPoint"); shift
@@ -140,18 +140,18 @@ do
 			while [ "$1" != ';' ]
 			do
 			    if [ $# -eq 0 ]; then
-				echo >&2 'ERROR: --exec must be concluded by ;'
-				echo >&2
-				printShortUsage "$0" >&2
+				echo 'ERROR: --exec must be concluded by ;'
+				echo
+				printUsage "$0"
 				exit 2
-			    fi
+			    fi >&2
 
 			    execCommand+=("$1"); shift
 			done
 			shift
 			;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		fileGlobs+=("$1"); shift;;
     esac
 done
diff --git a/bin/lastFiles b/bin/lastFiles
--- a/bin/lastFiles
+++ b/bin/lastFiles
@@ -11,7 +11,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -53,7 +53,7 @@ do
 			shift; sentinelMissingCount="$1"; shift;;
 	--count|-c)	shift; count="$1"; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -62,7 +62,7 @@ if [ ${#globs[@]} -gt 0 ]; then
     if [ -n "${count+t}" ]; then
 	echo 'ERROR: Cannot combine --after with --count.'
 	echo
-	printShortUsage "$0"
+	printUsage "$0"
 	exit 2
     fi >&2
 
diff --git a/bin/newestFiles b/bin/newestFiles
--- a/bin/newestFiles
+++ b/bin/newestFiles
@@ -12,7 +12,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -60,7 +60,7 @@ do
 	--include-epoch|-e)
 			shift; cutter=();;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -73,12 +73,12 @@ if [ ${#globs[@]} -gt 0 ]; then
     if [ -n "$sentinelAge" ]; then
 	echo 'ERROR: Cannot combine --newer-than with --newer.'
 	echo
-	printShortUsage "$0"
+	printUsage "$0"
 	exit 2
     elif [ -n "${count+t}" ]; then
 	echo 'ERROR: Cannot combine --newer with --count.'
 	echo
-	printShortUsage "$0"
+	printUsage "$0"
 	exit 2
     fi >&2
 
@@ -95,7 +95,7 @@ if [ ${#globs[@]} -gt 0 ]; then
 elif [ -n "${count+t}" -a -n "$sentinelAge" ]; then
     echo 'ERROR: Cannot combine --newer-than with --count.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 fi
 [ $# -gt 0 ] || set -- "$PWD"
