Minor: Support --

diff --git a/bin/getExecutableDetailsForDir b/bin/getExecutableDetailsForDir
--- a/bin/getExecutableDetailsForDir
+++ b/bin/getExecutableDetailsForDir
@@ -10,13 +10,19 @@ Determine the number of executable commands in DIR and print a message
 mentioning the first ${GETEXECUTABLEDETAILSFORDIR_MAX_SHOW_COMMANDS} of them.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] DIR [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] DIR [-?|-h|--help]'
 }
 isQuiet=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --quiet|-q)		shift; isQuiet=t;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--quiet|-q)	shift; isQuiet=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -ne 1 ]; then
     printUsage "$0" >&2
     exit 2
