hasglobmatch: ENH: Allow checking for unique match via -u|--unique
System-info: Ubuntu 24.04.3 LTS, x86_64
Platform-info: bash 5.2.21(1)-release

diff --git a/bin/hasglobmatch b/bin/hasglobmatch
--- a/bin/hasglobmatch
+++ b/bin/hasglobmatch
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "'FILE-GLOB' [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-u|--unique] 'FILE-GLOB' [...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -25,19 +25,42 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --unique|-u		Only succeed if a single file matches the passed
+			FILE-GLOB(s).
 SEE ALSO:
 - expandglob is hasglobmatch with printing all results.
 - hasMatchingFile matches in passed dir(s) and can search the entire directory
   tree(s).
 HELPTEXT
 }
-case "$1" in
-    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-esac
+
+isUniqueMatch=
+onMatch=succeed
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--unique|-u)	shift; isUniqueMatch=t; onMatch=incrementMatchCount;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
+
+succeed()
+{
+    exit 0
+}
+
+let matchCnt=0
+incrementMatchCount()
+{
+    let matchCnt+=1
+}
 
 IFS=$'\n'
 for arg
@@ -53,7 +76,7 @@ do
 	fi
     fi
 
-    [ -e "$arg" -o -h "$arg" ] && exit 0
+    [ -e "$arg" -o -h "$arg" ] && $onMatch
 
     # Still need to check for existing files; in case a FILE-GLOB without a
     # wildcard was passed, it's not eliminated by nullglob.
@@ -61,7 +84,8 @@ do
     typeset -a files=($arg)
     for f in "${files[@]}"
     do
-	[ -e "$f" -o  -h "$f" ] && exit 0
+	[ -e "$f" -o  -h "$f" ] && $onMatch
     done
 done
+[ "$isUniqueMatch" ] && [ $matchCnt -eq 1 ] && exit 0
 exit 1
