{namedbackup,writeOrigOrBackup,writeorig}: Adapt: writebackup now used my conventional exit statuses

diff --git a/bin/namedbackup b/bin/namedbackup
--- a/bin/namedbackup
+++ b/bin/namedbackup
@@ -73,8 +73,9 @@ HELPDESCRIPTION
 EXIT STATUS:
     0	Complete success.
     1	Failed to backup any FILE(s).
-    2	Partial success; some FILE(s) could not be backed up.
-    3	Bad invocation, wrong or missing command-line arguments.
+    2   Bad invocation, wrong or missing command-line arguments
+    3	Internal error or failed assertion.
+    6	Partial success; some FILE(s) could not be backed up.
 HELPTEXT
 }
 
@@ -116,7 +117,7 @@ do
 	--backup-dir|-d)
 			if [ -z "$2" ]; then
 			    { echo "ERROR: Must pass directory after ${1}!"; echo; printUsage "$0"; } >&2
-			    exit 3
+			    exit 2
 			fi
 			shift
 			backupDir="${1%/}/"
@@ -126,13 +127,13 @@ do
 	--delete-original)
 			shift; isDeleteOriginal=t;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
+	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
 if [ $# -eq 0 ]; then
     printUsage "$0"
-    exit 3
+    exit 2
 elif [ -z "$name" ]; then
     echo 'ERROR: No -n|--name NAME passed.'
     exit 2
@@ -148,7 +149,7 @@ if [ -n "$backupDirspec" -a ! -d "$backupDirspec" ]; then
 	mkdir --parents -- "$backupDirspec" || exit 3
     else
 	printf 'ERROR: Backup dir does not exist: "%s".\n' "${backupDir%/}"
-	exit 3
+	exit 2
     fi
 fi
 
@@ -295,5 +296,5 @@ do
 done
 
 if [ "$isFailure" ]; then
-    [ "$isSuccess" ] && exit 2 || exit 1
+    [ "$isSuccess" ] && exit 6 || exit 1
 fi
diff --git a/bin/writeOrigOrBackup b/bin/writeOrigOrBackup
--- a/bin/writeOrigOrBackup
+++ b/bin/writeOrigOrBackup
@@ -54,9 +54,10 @@ HELPDESCRIPTION
 				exit status 1.
 EXIT STATUS:
     0	Complete success.
-    1	Failed to backup any file(s).
-    2	Partial success; some file(s) could not be backed up.
-    3	Bad invocation, wrong or missing command-line arguments.
+    1	Failed to backup any FILE(s).
+    2   Bad invocation, wrong or missing command-line arguments
+    3	Internal error or failed assertion.
+    6	Partial success; some FILE(s) could not be backed up.
 HELPTEXT
 }
 
@@ -80,7 +81,7 @@ do
 	--accept-nonexisting)
 			anyBackupArgs+=("$1"); shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
+	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -113,5 +114,5 @@ do
 done
 
 if [ "$isFailure" ]; then
-    [ "$isSuccess" ] && exit 2 || exit 1
+    [ "$isSuccess" ] && exit 6 || exit 1
 fi
diff --git a/bin/writeorig b/bin/writeorig
--- a/bin/writeorig
+++ b/bin/writeorig
@@ -58,9 +58,10 @@ HELPDESCRIPTION
 EXIT STATUS:
     0	Complete success, or backup already exists and -k|--keep is given, or
 	the backup is from today and --once-today is given.
-    1	Failed to backup any file(s).
-    2	Partial success; some file(s) could not be backed up.
-    3	Bad invocation, wrong or missing command-line arguments.
+    1	Failed to backup any FILE(s).
+    2   Bad invocation, wrong or missing command-line arguments
+    3	Internal error or failed assertion.
+    6	Partial success; some FILE(s) could not be backed up.
 HELPTEXT
 }
 
@@ -82,7 +83,7 @@ do
 	--backup-dir|-d)
 			if [ -z "$2" ]; then
 			    { echo "ERROR: Must pass directory after ${1}!"; echo; printUsage "$0"; } >&2
-			    exit 3
+			    exit 2
 			fi
 			shift
 			backupDir="${1%/}/"
@@ -97,7 +98,7 @@ do
 	--accept-nonexisting)
 			shift; isAcceptNonexisting=t;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
+	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -116,7 +117,7 @@ elif [ "$isOnlyPrintExtension" ] && [ "$isDeleteOriginal" ]; then
     exit 2
 elif [ -n "$backupDir" -a ! -d "${backupDir%/}" ]; then
     printf 'ERROR: Backup dir does not exist: "%s"!\n' "${backupDir%/}"
-    exit 3
+    exit 2
 fi >&2
 
 printBackupFile()
@@ -201,5 +202,5 @@ do
 done
 
 if [ "$isFailure" ]; then
-    [ "$isSuccess" ] && exit 2 || exit 1
+    [ "$isSuccess" ] && exit 6 || exit 1
 fi
