ENH: Support -p|--parents for TARGETDIR

diff --git a/bin/namedrestore b/bin/namedrestore
--- a/bin/namedrestore
+++ b/bin/namedrestore
@@ -18,7 +18,7 @@ shopt -qs nullglob
 
 printShortUsage()
 {
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-t|--to DIRSPEC] [-C|--clobber|-f|--force|-i|--interactive|-n|--no-clobber] [--archive-program "unzip" [--archive-extension .zip] [--archive-flag-list FLAG] [--archive-flag-force FLAG] [--archive-flag-interactive FLAG] [--archive-flag-no-clobber FLAG]] [--basedir BASEDIR|--base-type config|data|runtime|cache|temp] [--backup-dir|-d DIR] [--delete-backup] [--] BACKUP-NAME|BACKUP-FILE [...] [--help|-h|-?]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-t|--to DIRSPEC [-p|--parents]] [-C|--clobber|-f|--force|-i|--interactive|-n|--no-clobber] [--archive-program "unzip" [--archive-extension .zip] [--archive-flag-list FLAG] [--archive-flag-force FLAG] [--archive-flag-interactive FLAG] [--archive-flag-no-clobber FLAG]] [--basedir BASEDIR|--base-type config|data|runtime|cache|temp] [--backup-dir|-d DIR] [--delete-backup] [--] BACKUP-NAME|BACKUP-FILE [...] [--help|-h|-?]'
 }
 printUsage()
 {
@@ -42,6 +42,8 @@ HELPDESCRIPTION
     cat <<HELPTEXT
     --to|-t DIRSPEC	The target directory (by default the current working
 			dir).
+    --parents|-p	Make parent directories for the target directory as
+			needed.
     --clobber|-C	Remove all existing directories that the archive
 			contains before forcefully restoring the archive.
 			In contrast to --force, this also gets rid of files in
@@ -76,6 +78,7 @@ HELPTEXT
 }
 
 targetDirspec=
+isMakeParents=t
 isClobber=
 overwritePolicy=interactive
 baseDir=
@@ -106,6 +109,7 @@ do
 			shift
 			;;
 	--to|-t)	shift; targetDirspec="$1"; shift;;
+	--parents|-p)	shift; isMakeParents=t;;
 	--clobber|-C)	shift; isClobber=t; overwritePolicy=force;;
 	--force|-f)	shift; overwritePolicy=force;;
 	--interactive|-i)
@@ -155,6 +159,18 @@ if [ -n "$backupDirspec" -a ! -d "$backupDirspec" ]; then
     exit 2
 fi
 
+ensureTargetDir()
+{
+    if [ -n "$targetDirspec" -a ! -d "$targetDirspec" ]; then
+	if [ "$isMakeParents" ]; then
+	    mkdir --parents -- "$targetDirspec" || exit 3
+	else
+	    printf 'ERROR: Target dir does not exist: "%s".\n' "${targetDirspec%/}"
+	    exit 2
+	fi
+    fi
+}
+
 extractArchive()
 {
     local filespec="${1:?}"; shift
@@ -184,6 +200,9 @@ extractArchive()
 restoreArchive()
 {
     local filespec="${1:?}"; shift
+
+    ensureTargetDir || return $?
+
     if [ -n "$targetDirspec" -a "$targetDirspec" != '.' ]; then
 	filespec="$(readlink -nf -- "$filespec")" || return $?
 	(
@@ -204,6 +223,8 @@ restoreFile()
     local filespec="${1:?}"; shift
     local filename="$(basename -- "$filespec")"
     local destination="${targetDirspec%/}${targetDirspec:+/}${filename#*$NAMEDBACKUP_FILE_SEPARATOR}"
+
+    ensureTargetDir || return $?
 
     if [ "$isDeleteBackup" ]; then
 	mv --verbose --$overwritePolicy -- "$filespec" "$destination"
