pathglob: Cosmetics: Change quoting and period of error message

diff --git a/bin/pathglob b/bin/pathglob
--- a/bin/pathglob
+++ b/bin/pathglob
@@ -33,7 +33,7 @@ do
     esac
 done
 if [ $# -eq 0 ]; then
-    echo >&2 "ERROR: Missing GLOB argument!"
+    echo >&2 'ERROR: Missing GLOB argument.'
     exit 2
 fi
 typeset -a shortenPipeline=()
