touch-p: Robustness: Minor: Complain on unknown options

diff --git a/bin/touch-p b/bin/touch-p
--- a/bin/touch-p
+++ b/bin/touch-p
@@ -54,6 +54,7 @@ do
 	--no-update|-U)	shift; isUpdate=;;
 
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
