write{O,o}rig[OrBackup]: ENH: Only return the backup file extension with --get-extension

diff --git a/bin/writeOrigOrBackup b/bin/writeOrigOrBackup
--- a/bin/writeOrigOrBackup
+++ b/bin/writeOrigOrBackup
@@ -6,6 +6,8 @@ printShortUsage()
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--delete-original] [--once-today] [--] FILE [...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--delete-original] [--once-today] --ignore-no-files [--] [FILE [...]] [-?|-h|--help]'
+    echo
+    printf 'Usage: sed -i"$(%q %s)" -e ... FILE\n' "$(basename "$1")" '[--once-today] --get-extension FILE'
 }
 printUsage()
 {
@@ -37,6 +39,8 @@ HELPDESCRIPTION
 				acceptable.
     --once-today                A FILE is only backed up if no backup on the
                                 current day was already made.
+    --get-extension		Just print the backup extension (or nothing if
+				--once-today and a backup already exists).
 EXIT STATUS:
     0	Complete success.
     1	Failed to backup any file(s).
@@ -46,6 +50,8 @@ HELPTEXT
 }
 
 isIgnoreNoFiles=
+isDeleteOriginal=
+isOnlyPrintExtension=
 typeset -a anyBackupArgs=()
 typeset -a writebackupArgs=()
 while [ $# -ne 0 ]
@@ -53,19 +59,31 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--delete-original)
-			anyBackupArgs+=("$1"); shift;;
+			anyBackupArgs+=("$1"); shift; isDeleteOriginal=t;;
 	--once-today)	writebackupArgs+=("$1"); shift;;
 	--ignore-no-files)
 			shift; isIgnoreNoFiles=t;;
+	--get-extension)
+			anyBackupArgs+=("$1"); shift; isOnlyPrintExtension=t;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
 	*)		break;;
     esac
 done
 if [ $# -eq 0 ] && [ ! "$isIgnoreNoFiles" ]; then
-    printUsage "$0" >&2
+    printUsage "$0"
     exit 2
-fi
+elif [ "$isOnlyPrintExtension" ] && [ $# -ne 1 ]; then
+    echo 'ERROR: Only a single FILE can be passed with --get-extension.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ "$isOnlyPrintExtension" ] && [ "$isDeleteOriginal" ]; then
+    echo 'ERROR: Cannot combine --get-extension and --delete-original.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 
 
 isSuccess=
diff --git a/bin/writeorig b/bin/writeorig
--- a/bin/writeorig
+++ b/bin/writeorig
@@ -6,6 +6,8 @@ printShortUsage()
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-f|--overwrite|-k|--keep] [--delete-original] [--] FILE [...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-f|--overwrite|-k|--keep] [--delete-original] --ignore-no-files [--] [FILE [...]] [-?|-h|--help]'
+    echo
+    printf 'Usage: sed -i"$(%q %s)" -e ... FILE\n' "$(basename "$1")" '[-f|--overwrite|-k|--keep] --get-extension FILE'
 }
 printUsage()
 {
@@ -36,6 +38,8 @@ HELPDESCRIPTION
 				passed. Useful when passing a glob that may
 				resolve to no files at all, and that is
 				acceptable.
+    --get-extension		Just print the .orig backup extension (or
+				nothing if --keep and a backup already exists).
 EXIT STATUS:
     0	Complete success.
     1	Failed to backup any file(s).
@@ -47,6 +51,7 @@ HELPTEXT
 isOverwrite=
 isIgnoreNoFiles=
 isDeleteOriginal=
+isOnlyPrintExtension=
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -57,15 +62,27 @@ do
 			shift; isIgnoreNoFiles=t;;
 	--delete-original)
 			shift; isDeleteOriginal=t;;
+	--get-extension)
+			shift; isOnlyPrintExtension=t;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
 	*)		break;;
     esac
 done
 if [ $# -eq 0 ] && [ ! "$isIgnoreNoFiles" ]; then
-    printUsage "$0" >&2
+    printUsage "$0"
     exit 2
-fi
+elif [ "$isOnlyPrintExtension" ] && [ $# -ne 1 ]; then
+    echo 'ERROR: Only a single FILE can be passed with --get-extension.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ "$isOnlyPrintExtension" ] && [ "$isDeleteOriginal" ]; then
+    echo 'ERROR: Cannot combine --get-extension and --delete-original.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 
 writebackup()
 {
@@ -82,6 +99,10 @@ writebackup()
 	if [ "${backupFilespec}" ]; then
 	    if [ ! "$isOverwrite" ] && [ -f "$backupFilespec" ]; then
 		return 1
+	    fi
+	    if [ "$isOnlyPrintExtension" ]; then
+		printf '%s\n' ".${backupFilespec##*.}"
+		return 0
 	    fi
 
 	    umask 0111	# Drop the execute permission on the backup.
